CREATE TABLE ESTADO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(50),
    UF CHAR(2),

    CONSTRAINT PK_ESTADO PRIMARY KEY (ID)
);

CREATE TABLE CIDADE (
    ID INTEGER NOT NULL,
    NOME VARCHAR(50),
    ESTADOID INTEGER,

    CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
    CONSTRAINT FK_CIDADE_ESTADO
        FOREIGN KEY (ESTADOID)
        REFERENCES ESTADO (ID)
);

CREATE TABLE CLIENTE (
	ID INTEGER NOT NULL,
	NOME VARCHAR(80),
	CEP CHAR(8),
	CPF_CNPJ VARCHAR(14),
	ENDERECO VARCHAR(100),
	NUMERO VARCHAR(20),
	COMPLEMENTO VARCHAR(60),
	BAIRRO VARCHAR(100),
	CIDADE INTEGER,
	DATANASCIMENTO DATE,
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_CLIENTE_CIDADE
		FOREIGN KEY (CIDADE)
		REFERENCES CIDADE (ID)
);